// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuditFilterInput struct {
	Page   *int32  `json:"page,omitempty"`
	Limit  *int32  `json:"limit,omitempty"`
	Action *string `json:"action,omitempty"`
	Entity *string `json:"entity,omitempty"`
	Status *string `json:"status,omitempty"`
	UserID *string `json:"userId,omitempty"`
}

type AuditLog struct {
	ID           string    `json:"id"`
	UserID       *string   `json:"userId,omitempty"`
	Action       string    `json:"action"`
	Entity       string    `json:"entity"`
	EntityID     *string   `json:"entityId,omitempty"`
	IPAddress    *string   `json:"ipAddress,omitempty"`
	RequestData  *string   `json:"requestData,omitempty"`
	ResponseData *string   `json:"responseData,omitempty"`
	Status       *string   `json:"status,omitempty"`
	ErrorMessage *string   `json:"errorMessage,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

type AuditLogPagination struct {
	Items []*AuditLog     `json:"items"`
	Meta  *PaginationMeta `json:"meta"`
}

type Mutation struct {
}

type PaginationMeta struct {
	Page        int32 `json:"page"`
	Limit       int32 `json:"limit"`
	TotalData   int32 `json:"totalData"`
	TotalPage   int32 `json:"totalPage"`
	HasNext     bool  `json:"hasNext"`
	HasPrevious bool  `json:"hasPrevious"`
}

type Query struct {
}

type UpdateUserInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}
