package modules

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/internal/graphql/mapper"
	"backend/internal/graphql/model"
	"context"
)

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, filter *model.AuditFilterInput) (*model.AuditLogPagination, error) {
	auditFilter, err := mapper.ToAuditFilterInput(filter)
	if err != nil {
		return nil, err
	}

	auditFilter.Normalize()

	logs, total, err := r.Resolver.AuditService.GetAuditLogs(ctx, auditFilter)
	if err != nil {
		return nil, err
	}

	items := make([]*model.AuditLog, 0, len(logs))
	for i := range logs {
		items = append(items, mapper.ToGraphQLAuditLog(&logs[i]))
	}

	meta := mapper.BuildAuditPaginationMeta(auditFilter.Page, auditFilter.Limit, total)

	return &model.AuditLogPagination{
		Items: items,
		Meta:  meta,
	}, nil
}
