package modules

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/internal/graphql/generated"
	"backend/internal/graphql/model"
	"backend/internal/middleware"
	auditDTO "backend/internal/modules/audit/dto"
	auditlogger "backend/internal/modules/audit/logger"
	"backend/internal/modules/auth/dto"
	"context"
	"fmt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input dto.RegisterInput) (*dto.User, error) {
	user, err := r.Resolver.AuthService.Register(ctx, input)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		Action:       "REGISTER",
		Entity:       "AUTH",
		RequestData:  auditlogger.EncodeData(input),
		ResponseData: auditlogger.EncodeData(user),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return user, err
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input dto.LoginInput) (*dto.AuthPayload, error) {
	payload, err := r.Resolver.AuthService.Login(ctx, input)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		Action:       "LOGIN",
		Entity:       "AUTH",
		RequestData:  auditlogger.EncodeData(input),
		ResponseData: auditlogger.EncodeData(payload),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return payload, err
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*dto.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (bool, error) {
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*dto.User, error) {
	userID, err := middleware.RequireUserID(ctx)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			Action:       "ME",
			Entity:       "AUTH",
			RequestData:  "",
			ResponseData: "",
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}

	user, err := r.Resolver.AuthService.Me(ctx, userID)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		UserID:       &userID,
		Action:       "ME",
		Entity:       "AUTH",
		ResponseData: auditlogger.EncodeData(user),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return user, err
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *dto.User) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
