package modules

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/internal/graphql/generated"
	"backend/internal/middleware"
	auditDTO "backend/internal/modules/audit/dto"
	auditlogger "backend/internal/modules/audit/logger"
	"backend/internal/modules/project/dto"
	projectservice "backend/internal/modules/project/service"
	"context"
	"fmt"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input dto.CreateProjectInput) (*dto.Project, error) {
	userID, err := middleware.RequireUserID(ctx)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			Action:       "CREATE_PROJECT",
			Entity:       "PROJECT",
			RequestData:  auditlogger.EncodeData(input),
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}

	project, err := r.Resolver.ProjectService.CreateProject(ctx, userID, input)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		UserID:       &userID,
		Action:       "CREATE_PROJECT",
		Entity:       "PROJECT",
		RequestData:  auditlogger.EncodeData(input),
		ResponseData: auditlogger.EncodeData(project),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return project, err
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input dto.UpdateProjectInput) (*dto.Project, error) {
	userID, err := middleware.RequireUserID(ctx)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			Action:       "UPDATE_PROJECT",
			Entity:       "PROJECT",
			EntityID:     auditlogger.ParseUintPointer(id),
			RequestData:  auditlogger.EncodeData(input),
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}

	projectID, err := projectservice.ParseProjectID(id)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			UserID:       &userID,
			Action:       "UPDATE_PROJECT",
			Entity:       "PROJECT",
			RequestData:  auditlogger.EncodeData(input),
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}

	project, err := r.Resolver.ProjectService.UpdateProject(ctx, userID, projectID, input)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		UserID:       &userID,
		EntityID:     &projectID,
		Action:       "UPDATE_PROJECT",
		Entity:       "PROJECT",
		RequestData:  auditlogger.EncodeData(input),
		ResponseData: auditlogger.EncodeData(project),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return project, err
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	userID, err := middleware.RequireUserID(ctx)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			Action:       "DELETE_PROJECT",
			Entity:       "PROJECT",
			EntityID:     auditlogger.ParseUintPointer(id),
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return false, err
	}

	projectID, err := projectservice.ParseProjectID(id)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			UserID:       &userID,
			Action:       "DELETE_PROJECT",
			Entity:       "PROJECT",
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return false, err
	}

	if err := r.Resolver.ProjectService.DeleteProject(ctx, userID, projectID); err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			UserID:       &userID,
			EntityID:     &projectID,
			Action:       "DELETE_PROJECT",
			Entity:       "PROJECT",
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return false, err
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		UserID:   &userID,
		EntityID: &projectID,
		Action:   "DELETE_PROJECT",
		Entity:   "PROJECT",
		Status:   "SUCCESS",
	})

	return true, nil
}

// ID is the resolver for the id field.
func (r *projectResolver) ID(ctx context.Context, obj *dto.Project) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, filter *dto.ProjectFilterInput) (*dto.ProjectPagination, error) {
	var projectFilter dto.ProjectFilterInput
	if filter != nil {
		projectFilter = *filter
	}

	projects, err := r.Resolver.ProjectService.GetAllProjects(ctx, projectFilter)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		Action:       "LIST_PROJECTS",
		Entity:       "PROJECT",
		RequestData:  auditlogger.EncodeData(filter),
		ResponseData: auditlogger.EncodeData(projects),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return projects, err
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*dto.Project, error) {
	projectID, err := projectservice.ParseProjectID(id)
	if err != nil {
		auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
			Action:       "GET_PROJECT",
			Entity:       "PROJECT",
			EntityID:     auditlogger.ParseUintPointer(id),
			Status:       "FAILED",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}

	project, err := r.Resolver.ProjectService.GetProjectByID(ctx, projectID)
	status := "SUCCESS"
	errorMessage := ""
	if err != nil {
		status = "FAILED"
		errorMessage = err.Error()
	}

	auditlogger.Record(r.Resolver.AuditService, ctx, auditDTO.CreateAuditLogInput{
		EntityID:     &projectID,
		Action:       "GET_PROJECT",
		Entity:       "PROJECT",
		ResponseData: auditlogger.EncodeData(project),
		Status:       auditlogger.NormalizeStatus(status),
		ErrorMessage: errorMessage,
	})

	return project, err
}

// Page is the resolver for the page field.
func (r *projectFilterInputResolver) Page(ctx context.Context, obj *dto.ProjectFilterInput, data *int32) error {
	panic(fmt.Errorf("not implemented: Page - page"))
}

// Limit is the resolver for the limit field.
func (r *projectFilterInputResolver) Limit(ctx context.Context, obj *dto.ProjectFilterInput, data *int32) error {
	panic(fmt.Errorf("not implemented: Limit - limit"))
}

// Project returns generated.ProjectResolver implementation.
func (r *Resolver) Project() generated.ProjectResolver { return &projectResolver{r} }

// ProjectFilterInput returns generated.ProjectFilterInputResolver implementation.
func (r *Resolver) ProjectFilterInput() generated.ProjectFilterInputResolver {
	return &projectFilterInputResolver{r}
}

type projectResolver struct{ *Resolver }
type projectFilterInputResolver struct{ *Resolver }
