package modules

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/internal/graphql/generated"
	"backend/internal/graphql/mapper"
	"backend/internal/modules/project/dto"
	projectservice "backend/internal/modules/project/service"
	"context"
)

// ID is the resolver for the id field.
func (r *projectResponsibilityResolver) ID(ctx context.Context, obj *dto.ProjectResponsibility) (string, error) {
	return mapper.FormatUint(obj.ID), nil
}

// SortOrder is the resolver for the sortOrder field.
func (r *projectResponsibilityResolver) SortOrder(ctx context.Context, obj *dto.ProjectResponsibility) (int32, error) {
	return int32(obj.SortOrder), nil
}

// SortOrder is the resolver for the sortOrder field.
func (r *createProjectResponsibilityInputResolver) SortOrder(ctx context.Context, obj *dto.CreateProjectResponsibilityInput, data *int32) error {
	if data != nil {
		obj.SortOrder = int(*data)
	}
	return nil
}

// ID is the resolver for the id field.
func (r *updateProjectResponsibilityInputResolver) ID(ctx context.Context, obj *dto.UpdateProjectResponsibilityInput, data *string) error {
	if data != nil {
		id, err := projectservice.ParseProjectID(*data)
		if err != nil {
			return err
		}
		obj.ID = &id
	}
	return nil
}

// SortOrder is the resolver for the sortOrder field.
func (r *updateProjectResponsibilityInputResolver) SortOrder(ctx context.Context, obj *dto.UpdateProjectResponsibilityInput, data *int32) error {
	if data != nil {
		obj.SortOrder = int(*data)
	}
	return nil
}

// ProjectResponsibility returns generated.ProjectResponsibilityResolver implementation.
func (r *Resolver) ProjectResponsibility() generated.ProjectResponsibilityResolver {
	return &projectResponsibilityResolver{r}
}

// CreateProjectResponsibilityInput returns generated.CreateProjectResponsibilityInputResolver implementation.
func (r *Resolver) CreateProjectResponsibilityInput() generated.CreateProjectResponsibilityInputResolver {
	return &createProjectResponsibilityInputResolver{r}
}

// UpdateProjectResponsibilityInput returns generated.UpdateProjectResponsibilityInputResolver implementation.
func (r *Resolver) UpdateProjectResponsibilityInput() generated.UpdateProjectResponsibilityInputResolver {
	return &updateProjectResponsibilityInputResolver{r}
}

type projectResponsibilityResolver struct{ *Resolver }
type createProjectResponsibilityInputResolver struct{ *Resolver }
type updateProjectResponsibilityInputResolver struct{ *Resolver }
