package modules

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"backend/internal/graphql/generated"
	"backend/internal/graphql/mapper"
	"backend/internal/modules/project/dto"
	"context"
)

// ID is the resolver for the id field.
func (r *projectDetailResolver) ID(ctx context.Context, obj *dto.ProjectDetail) (string, error) {
	return mapper.FormatUint(obj.ID), nil
}

// ProjectDetail returns generated.ProjectDetailResolver implementation.
func (r *Resolver) ProjectDetail() generated.ProjectDetailResolver { return &projectDetailResolver{r} }

type projectDetailResolver struct{ *Resolver }
